### ISSUE TITLE
Important things TODO

### ISSUE THREAD

**Issue by shoghicp** [PocketMine/RubberBand#1]
- [ ] Detect version and forward properly to supporting servers
- [ ] New tokens generated each 15 seconds, valid for 30 seconds.
- [ ] Helper threads for background tasks in proxy.
- [ ] Multiworld compatible.
- [ ] 5-second server pingback with player list, information.
- [ ] Servers can be regrouped or split in runtime.
- [ ] Support DEFLATEPacket
- [ ] REUSE_ADDR for UDP.
- [ ] Maintain client <--> server for 2 minutes before resetting it to the lobby.
- [ ] Remote Management Tool (sends UDP packets with API key)
  - Broadcast message
  - Run commands on servers
  - Change API key on runtime

**Comment by iksaku** [comment]
Wow! Congratulations @shoghicp ! You are carrying MCPE multiplayer to a whole new level with PocketMine-MP!
P.S: If you want a beta tester contact me, I can help you if you want ;)

Cheers!
You are the best! :D

**Comment by ghost** [comment]
You should make it be able to switch servers. :)

**Comment by Mrtannn** [comment]
Waiting for this plugin.

Cheers.

**Comment by ghost** [comment]
When is the release expected to be?

**Comment by ghost** [comment]
Also please add "/server" command. :)

**Comment by L3ice** [comment]
Cmon
Work on Rubberband! :D

**Comment by ghost** [comment]
@MineMobileCrafter He can't finish it until he implements the new networking into PocketMine-MP.  Just be patient.

**Comment by Glitchmaster-PE** [comment]
If you want it done as fast as you want, do it yourself ;)

**Comment by iksaku** [comment]
No one can do this better than @shoghicp

**Comment by ghost** [comment]
Yea @shoghicp is a professional of networking stuff and he is much better than me. XD 
I made cool plugins because of his awesome easy-to-use APIs.

**Comment by iksaku** [comment]
[SUGGESTION] A main console that control each one... so if I do "/say hi" on the main one... it will be send to every server

**Comment by shoghicp** [comment]
I'm implementing a new way to do networking into PocketMine-MP. With that, plugins will be able to block/modify/create packets easily, route them, and it will be more efficient. Using that, I'll be able to use a single TCP socket to communicate frontend <--> backend server, eliminating the random crashes and making the connection even more reliable.

Just wait, I've to finish my tests :D

**Comment by ghost** [comment]
@shoghicp You're the best! :D Looking forwards to your release. :)

**Comment by ghost** [comment]
im making the same API and same thing and go on shoghicp! the API that i will make would be for networking and that and a plugin for Multi-Server that i will not release cuz im banned from the forums :P

**Comment by iksaku** [comment]
@shoghicp Cool!

**Comment by iksaku** [comment]
@JassperBeastHD I don't think so... (https://github.com/PocketMine/RubberBand/issues/6)

**Comment by ghost** [comment]
@shoghicp There are some limits of using a single TCP connection, maybe you should make it dynamicly.

**Comment by AndreyNazarchuk** [comment]
Still working on this anymore?
Really look forward to linking servers :)

**Comment by shoghicp** [comment]
I'll work on this after finishing 1.4 :)

**Comment by ghost** [comment]
Since 1.4 is considered stable now, you should definitely work on this. :)
Would be really cool.

**Comment by iksaku** [comment]
^^^ :+1: ^^^

**Comment by AndreyNazarchuk** [comment]
:+1:
